Document: libhel
Title: Debian libhel Manual
Author: <insert document author here>
Abstract: This manual describes what libhel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libhel/libhel.sgml.gz

Format: postscript
Files: /usr/share/doc/libhel/libhel.ps.gz

Format: text
Files: /usr/share/doc/libhel/libhel.text.gz

Format: HTML
Index: /usr/share/doc/libhel/html/index.html
Files: /usr/share/doc/libhel/html/*.html

  
