# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mongoose/Projects/freyja_0.9.5

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mongoose/Projects/freyja_0.9.5

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake

# Special rule for the target install/local
install/local/fast: install/local

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mongoose/Projects/freyja_0.9.5/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mongoose/Projects/freyja_0.9.5/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named luawrapper

# Build rule for target.
luawrapper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 luawrapper

# fast build rule for target.
luawrapper/fast:
	$(MAKE) -f lua/CMakeFiles/luawrapper.dir/build.make lua/CMakeFiles/luawrapper.dir/build

#=============================================================================
# Target rules for targets named hel-0.2.2

# Build rule for target.
hel-0.2.2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hel-0.2.2

# fast build rule for target.
hel-0.2.2/fast:
	$(MAKE) -f libhel/CMakeFiles/hel-0.2.2.dir/build.make libhel/CMakeFiles/hel-0.2.2.dir/build

#=============================================================================
# Target rules for targets named mat44

# Build rule for target.
mat44: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mat44

# fast build rule for target.
mat44/fast:
	$(MAKE) -f libhel/CMakeFiles/mat44.dir/build.make libhel/CMakeFiles/mat44.dir/build

#=============================================================================
# Target rules for targets named ray

# Build rule for target.
ray: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ray

# fast build rule for target.
ray/fast:
	$(MAKE) -f libhel/CMakeFiles/ray.dir/build.make libhel/CMakeFiles/ray.dir/build

#=============================================================================
# Target rules for targets named freyja-0.9.5

# Build rule for target.
freyja-0.9.5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freyja-0.9.5

# fast build rule for target.
freyja-0.9.5/fast:
	$(MAKE) -f libfreyja/CMakeFiles/freyja-0.9.5.dir/build.make libfreyja/CMakeFiles/freyja-0.9.5.dir/build

#=============================================================================
# Target rules for targets named mgtk

# Build rule for target.
mgtk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mgtk

# fast build rule for target.
mgtk/fast:
	$(MAKE) -f libmgtk/CMakeFiles/mgtk.dir/build.make libmgtk/CMakeFiles/mgtk.dir/build

#=============================================================================
# Target rules for targets named mgtk-0.1.1

# Build rule for target.
mgtk-0.1.1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mgtk-0.1.1

# fast build rule for target.
mgtk-0.1.1/fast:
	$(MAKE) -f libmgtk/CMakeFiles/mgtk-0.1.1.dir/build.make libmgtk/CMakeFiles/mgtk-0.1.1.dir/build

#=============================================================================
# Target rules for targets named freyja

# Build rule for target.
freyja: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 freyja

# fast build rule for target.
freyja/fast:
	$(MAKE) -f freyja/CMakeFiles/freyja.dir/build.make freyja/CMakeFiles/freyja.dir/build

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... luawrapper"
	@echo "... hel-0.2.2"
	@echo "... mat44"
	@echo "... ray"
	@echo "... freyja-0.9.5"
	@echo "... mgtk"
	@echo "... mgtk-0.1.1"
	@echo "... freyja"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

