Document: freyja
Title: Debian freyja Manual
Author: <insert document author here>
Abstract: This manual describes what freyja is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freyja/freyja.sgml.gz

Format: postscript
Files: /usr/share/doc/freyja/freyja.ps.gz

Format: text
Files: /usr/share/doc/freyja/freyja.text.gz

Format: HTML
Index: /usr/share/doc/freyja/html/index.html
Files: /usr/share/doc/freyja/html/*.html

  
