Document: libfreyja
Title: Debian libfreyja Manual
Author: <insert document author here>
Abstract: This manual describes what libfreyja is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libfreyja/libfreyja.sgml.gz

Format: postscript
Files: /usr/share/doc/libfreyja/libfreyja.ps.gz

Format: text
Files: /usr/share/doc/libfreyja/libfreyja.text.gz

Format: HTML
Index: /usr/share/doc/libfreyja/html/index.html
Files: /usr/share/doc/libfreyja/html/*.html

  
