/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: t; c-basic-offset: 4 -*- */
/*===========================================================================
 * 
 * Project : freyja
 * Author  : Terry 'Mongoose' Hendrix II
 * Website : http://www.icculus.org/freyja/
 * Email   : mongooseichiban@gmail.com
 * Object  : 
 * License : No use w/o permission (C) 2004-2006 Mongoose
 * Comments: This is the Python plugin ABI.
 *
 *           This file was generated by Mongoose's UpdateBindings.py
 *           - Mongoose <mongooseichiban@gmail.com>
 *
 * 2006.12.11:
 * Mongoose - Generated, Based on C ABI for freyja
 ==========================================================================*/
#include <python2.4/Python.h>
#include "freyja.h"


PyMethodDef Plugin_methods[] = {
	{ "freyjaSkeletonCreate", py_freyjaSkeletonCreate, METH_VARARGS },
	{ "freyjaSkeletonPoolClear", py_freyjaSkeletonPoolClear, METH_VARARGS },
	{ "freyjaSkeletonDelete", py_freyjaSkeletonDelete, METH_VARARGS },
	{ "freyjaSkeletonUpdateBones", py_freyjaSkeletonUpdateBones, METH_VARARGS },
	{ "freyjaSkeletonAddBone", py_freyjaSkeletonAddBone, METH_VARARGS },
	{ "freyjaSkeletonRootIndex", py_freyjaSkeletonRootIndex, METH_VARARGS },
	{ "freyjaSkeletonTransform", py_freyjaSkeletonTransform, METH_VARARGS },
	{ "freyjaGetSkeletonCount", py_freyjaGetSkeletonCount, METH_VARARGS },
	{ "freyjaGetSkeletonBoneCount", py_freyjaGetSkeletonBoneCount, METH_VARARGS },
	{ "freyjaGetSkeletonBoneIndex", py_freyjaGetSkeletonBoneIndex, METH_VARARGS },
	{ "freyjaGetSkeletonRootIndex", py_freyjaGetSkeletonRootIndex, METH_VARARGS },
	{ "freyjaSkeletonName", py_freyjaSkeletonName, METH_VARARGS },
	{ "freyjaGetSkeletonName", py_freyjaGetSkeletonName, METH_VARARGS },
	{ "freyjaKeyFrameGroupCreate", py_freyjaKeyFrameGroupCreate, METH_VARARGS },
	{ "freyjaKeyFrameGroupDelete", py_freyjaKeyFrameGroupDelete, METH_VARARGS },
	{ "freyjaGetKeyFrameCount", py_freyjaGetKeyFrameCount, METH_VARARGS },
	{ "freyjaKeyFramePoolClear", py_freyjaKeyFramePoolClear, METH_VARARGS },
	{ "freyjaKeyFrameGetIndexFromId", py_freyjaKeyFrameGetIndexFromId, METH_VARARGS },
	{ "freyjaKeyFrameCreate", py_freyjaKeyFrameCreate, METH_VARARGS },
	{ "freyjaKeyFrameDelete", py_freyjaKeyFrameDelete, METH_VARARGS },
	{ "freyjaKeyFrameTime", py_freyjaKeyFrameTime, METH_VARARGS },
	{ "freyjaGetKeyFrameTime", py_freyjaGetKeyFrameTime, METH_VARARGS },
	{ "freyjaKeyFrameFlags", py_freyjaKeyFrameFlags, METH_VARARGS },
	{ "freyjaGetKeyFrameFlags", py_freyjaGetKeyFrameFlags, METH_VARARGS },
	{ "freyjaKeyFrameTransform", py_freyjaKeyFrameTransform, METH_VARARGS },
	{ "freyjaGetModelCount", py_freyjaGetModelCount, METH_VARARGS },
	{ "freyjaModelCreate", py_freyjaModelCreate, METH_VARARGS },
	{ "freyjaModelAddSkeleton", py_freyjaModelAddSkeleton, METH_VARARGS },
	{ "freyjaModelAddMesh", py_freyjaModelAddMesh, METH_VARARGS },
	{ "freyjaGetModelFlags", py_freyjaGetModelFlags, METH_VARARGS },
	{ "freyjaGetModelMeshCount", py_freyjaGetModelMeshCount, METH_VARARGS },
	{ "freyjaGetModelMeshIndex", py_freyjaGetModelMeshIndex, METH_VARARGS },
	{ "freyjaGetModelSkeleton", py_freyjaGetModelSkeleton, METH_VARARGS },
	{ "freyjaModelTransform", py_freyjaModelTransform, METH_VARARGS },
	{ "freyjaModelClear", py_freyjaModelClear, METH_VARARGS },
	{ "freyjaGetBoneCount", py_freyjaGetBoneCount, METH_VARARGS },
	{ "freyjaBonePoolClear", py_freyjaBonePoolClear, METH_VARARGS },
	{ "freyjaBoneCreate", py_freyjaBoneCreate, METH_VARARGS },
	{ "freyjaBoneDelete", py_freyjaBoneDelete, METH_VARARGS },
	{ "freyjaBoneFlags", py_freyjaBoneFlags, METH_VARARGS },
	{ "freyjaBoneParent", py_freyjaBoneParent, METH_VARARGS },
	{ "after", py_after, METH_VARARGS },
	{ "freyjaBoneName", py_freyjaBoneName, METH_VARARGS },
	{ "freyjaBoneRemoveChild", py_freyjaBoneRemoveChild, METH_VARARGS },
	{ "freyjaBoneAddChild", py_freyjaBoneAddChild, METH_VARARGS },
	{ "freyjaBoneTranslate3f", py_freyjaBoneTranslate3f, METH_VARARGS },
	{ "freyjaBoneTranslate3fv", py_freyjaBoneTranslate3fv, METH_VARARGS },
	{ "freyjaBoneRotateEuler3f", py_freyjaBoneRotateEuler3f, METH_VARARGS },
	{ "freyjaBoneRotateEuler3fv", py_freyjaBoneRotateEuler3fv, METH_VARARGS },
	{ "freyjaBoneRotateQuat4f", py_freyjaBoneRotateQuat4f, METH_VARARGS },
	{ "freyjaBoneRotateQuat4fv", py_freyjaBoneRotateQuat4fv, METH_VARARGS },
	{ "freyjaGetBoneRotationQuat4fv", py_freyjaGetBoneRotationQuat4fv, METH_VARARGS },
	{ "freyjaGetBoneRotationEuler3fv", py_freyjaGetBoneRotationEuler3fv, METH_VARARGS },
	{ "freyjaBoneTransform", py_freyjaBoneTransform, METH_VARARGS },
	{ "freyjaBoneTransform3fv", py_freyjaBoneTransform3fv, METH_VARARGS },
	{ "freyjaGetBoneNameString", py_freyjaGetBoneNameString, METH_VARARGS },
	{ "freyjaGetBoneName", py_freyjaGetBoneName, METH_VARARGS },
	{ "freyjaGetBoneParent", py_freyjaGetBoneParent, METH_VARARGS },
	{ "freyjaGetBoneBindPose16fv", py_freyjaGetBoneBindPose16fv, METH_VARARGS },
	{ "freyjaGetBoneWorldPos3fv", py_freyjaGetBoneWorldPos3fv, METH_VARARGS },
	{ "freyjaGetBoneTranslation3fv", py_freyjaGetBoneTranslation3fv, METH_VARARGS },
	{ "freyjaGetBoneSkeletonIndex", py_freyjaGetBoneSkeletonIndex, METH_VARARGS },
	{ "freyjaGetBoneChild", py_freyjaGetBoneChild, METH_VARARGS },
	{ "freyjaGetBoneChildCount", py_freyjaGetBoneChildCount, METH_VARARGS },
	{ "freyjaBoneUpdateBindPose", py_freyjaBoneUpdateBindPose, METH_VARARGS },
	{ "freyjaBoneGetBindTransform", py_freyjaBoneGetBindTransform, METH_VARARGS },
	{ "freyjaBoneGetBindTransformInverse", py_freyjaBoneGetBindTransformInverse, METH_VARARGS },
	{ "freyjaBoneBindTransformVertex", py_freyjaBoneBindTransformVertex, METH_VARARGS },
	{ "freyjaBoneTrackNew", py_freyjaBoneTrackNew, METH_VARARGS },
	{ "freyjaBoneTrackDuration", py_freyjaBoneTrackDuration, METH_VARARGS },
	{ "freyjaBoneTrackRate", py_freyjaBoneTrackRate, METH_VARARGS },
	{ "freyjaBoneKeyFrameNew", py_freyjaBoneKeyFrameNew, METH_VARARGS },
	{ "freyjaBonePosKeyFrame3f", py_freyjaBonePosKeyFrame3f, METH_VARARGS },
	{ "freyjaBoneRotKeyFrameEuler3f", py_freyjaBoneRotKeyFrameEuler3f, METH_VARARGS },
	{ "freyjaBoneRotKeyFrameQuat4f", py_freyjaBoneRotKeyFrameQuat4f, METH_VARARGS },
	{ "freyjaGetBoneClass", py_freyjaGetBoneClass, METH_VARARGS },
	{ "freyjaBoneLoadChunkJA", py_freyjaBoneLoadChunkJA, METH_VARARGS },
	{ "freyjaBoneSaveChunkJA", py_freyjaBoneSaveChunkJA, METH_VARARGS },
	{ "freyjaBoneSaveChunkTextJA", py_freyjaBoneSaveChunkTextJA, METH_VARARGS },
	{ "freyjaBoneLoadChunkTextJA", py_freyjaBoneLoadChunkTextJA, METH_VARARGS },
	{ "freyjaLightCreate", py_freyjaLightCreate, METH_VARARGS },
	{ "freyjaGetLightCount", py_freyjaGetLightCount, METH_VARARGS },
	{ "freyjaLightDelete", py_freyjaLightDelete, METH_VARARGS },
	{ "freyjaLightPosition4v", py_freyjaLightPosition4v, METH_VARARGS },
	{ "freyjaLightAmbient", py_freyjaLightAmbient, METH_VARARGS },
	{ "freyjaLightDiffuse", py_freyjaLightDiffuse, METH_VARARGS },
	{ "freyjaLightSpecular", py_freyjaLightSpecular, METH_VARARGS },
	{ "freyjaGetLightPosition4v", py_freyjaGetLightPosition4v, METH_VARARGS },
	{ "freyjaGetLightAmbient", py_freyjaGetLightAmbient, METH_VARARGS },
	{ "freyjaGetLightDiffuse", py_freyjaGetLightDiffuse, METH_VARARGS },
	{ "freyjaGetLightSpecular", py_freyjaGetLightSpecular, METH_VARARGS },
	{ "freyjaMaterialCreate", py_freyjaMaterialCreate, METH_VARARGS },
	{ "freyjaMaterialClearAll", py_freyjaMaterialClearAll, METH_VARARGS },
	{ "freyjaGetMaterialCount", py_freyjaGetMaterialCount, METH_VARARGS },
	{ "freyjaGetMaterialIndex", py_freyjaGetMaterialIndex, METH_VARARGS },
	{ "freyjaGetMaterialName", py_freyjaGetMaterialName, METH_VARARGS },
	{ "freyjaGetMaterialFlags", py_freyjaGetMaterialFlags, METH_VARARGS },
	{ "freyjaGetMaterialTexture", py_freyjaGetMaterialTexture, METH_VARARGS },
	{ "freyjaGetMaterialTextureName", py_freyjaGetMaterialTextureName, METH_VARARGS },
	{ "freyjaGetMaterialAmbient", py_freyjaGetMaterialAmbient, METH_VARARGS },
	{ "freyjaGetMaterialDiffuse", py_freyjaGetMaterialDiffuse, METH_VARARGS },
	{ "freyjaGetMaterialSpecular", py_freyjaGetMaterialSpecular, METH_VARARGS },
	{ "freyjaGetMaterialEmissive", py_freyjaGetMaterialEmissive, METH_VARARGS },
	{ "freyjaGetMaterialShininess", py_freyjaGetMaterialShininess, METH_VARARGS },
	{ "freyjaGetMaterialTransparency", py_freyjaGetMaterialTransparency, METH_VARARGS },
	{ "freyjaGetMaterialBlendSource", py_freyjaGetMaterialBlendSource, METH_VARARGS },
	{ "freyjaGetMaterialBlendDestination", py_freyjaGetMaterialBlendDestination, METH_VARARGS },
	{ "freyjaMaterialName", py_freyjaMaterialName, METH_VARARGS },
	{ "freyjaMaterialClearFlag", py_freyjaMaterialClearFlag, METH_VARARGS },
	{ "freyjaMaterialSetFlag", py_freyjaMaterialSetFlag, METH_VARARGS },
	{ "freyjaMaterialFlags", py_freyjaMaterialFlags, METH_VARARGS },
	{ "freyjaMaterialTextureName", py_freyjaMaterialTextureName, METH_VARARGS },
	{ "freyjaMaterialTexture", py_freyjaMaterialTexture, METH_VARARGS },
	{ "freyjaMaterialAmbient", py_freyjaMaterialAmbient, METH_VARARGS },
	{ "freyjaMaterialDiffuse", py_freyjaMaterialDiffuse, METH_VARARGS },
	{ "freyjaMaterialSpecular", py_freyjaMaterialSpecular, METH_VARARGS },
	{ "freyjaMaterialEmissive", py_freyjaMaterialEmissive, METH_VARARGS },
	{ "freyjaMaterialShininess", py_freyjaMaterialShininess, METH_VARARGS },
	{ "freyjaMaterialTransparency", py_freyjaMaterialTransparency, METH_VARARGS },
	{ "freyjaMaterialBlendSource", py_freyjaMaterialBlendSource, METH_VARARGS },
	{ "freyjaMaterialBlendDestination", py_freyjaMaterialBlendDestination, METH_VARARGS },
	{ "freyjaGetMaterialClass", py_freyjaGetMaterialClass, METH_VARARGS },
	{ "freyjaMaterialLoadChunkTextJA", py_freyjaMaterialLoadChunkTextJA, METH_VARARGS },
	{ "freyjaPakBegin", py_freyjaPakBegin, METH_VARARGS },
	{ "freyjaPakAddDecoderFunction2s", py_freyjaPakAddDecoderFunction2s, METH_VARARGS },
	{ "ABI.", py_ABI., METH_VARARGS },
	{ "freyjaPakAddFullPathFile", py_freyjaPakAddFullPathFile, METH_VARARGS },
	{ "freyjaPakEnd", py_freyjaPakEnd, METH_VARARGS },
	{ "freyjaMeshCreate", py_freyjaMeshCreate, METH_VARARGS },
	{ "freyjaMeshCopy", py_freyjaMeshCopy, METH_VARARGS },
	{ "freyjaMeshDelete", py_freyjaMeshDelete, METH_VARARGS },
	{ "freyjaMeshMaterial", py_freyjaMeshMaterial, METH_VARARGS },
	{ "freyjaMeshPosition", py_freyjaMeshPosition, METH_VARARGS },
	{ "freyjaMeshName1s", py_freyjaMeshName1s, METH_VARARGS },
	{ "freyjaMeshFlags1u", py_freyjaMeshFlags1u, METH_VARARGS },
	{ "freyjaMeshTransform3fv", py_freyjaMeshTransform3fv, METH_VARARGS },
	{ "freyjaMeshVertexCreate3fv", py_freyjaMeshVertexCreate3fv, METH_VARARGS },
	{ "freyjaMeshVertexPos3fv", py_freyjaMeshVertexPos3fv, METH_VARARGS },
	{ "freyjaMeshVertexNormal3fv", py_freyjaMeshVertexNormal3fv, METH_VARARGS },
	{ "freyjaMeshTexCoordCreate2fv", py_freyjaMeshTexCoordCreate2fv, METH_VARARGS },
	{ "freyjaMeshTexCoordCreate2f", py_freyjaMeshTexCoordCreate2f, METH_VARARGS },
	{ "freyjaMeshTexCoordCreate3fv", py_freyjaMeshTexCoordCreate3fv, METH_VARARGS },
	{ "freyjaMeshTexCoordCreate3f", py_freyjaMeshTexCoordCreate3f, METH_VARARGS },
	{ "freyjaMeshTexCoord2fv", py_freyjaMeshTexCoord2fv, METH_VARARGS },
	{ "freyjaMeshVertexTexCoord3fv", py_freyjaMeshVertexTexCoord3fv, METH_VARARGS },
	{ "freyjaMeshClampTexCoords", py_freyjaMeshClampTexCoords, METH_VARARGS },
	{ "freyjaMeshTransformTexCoord", py_freyjaMeshTransformTexCoord, METH_VARARGS },
	{ "freyjaMeshPolygonCreate", py_freyjaMeshPolygonCreate, METH_VARARGS },
	{ "freyjaMeshPolygonDelete", py_freyjaMeshPolygonDelete, METH_VARARGS },
	{ "freyjaMeshPolygonAddVertex1i", py_freyjaMeshPolygonAddVertex1i, METH_VARARGS },
	{ "freyjaMeshPolygonAddTexCoord1i", py_freyjaMeshPolygonAddTexCoord1i, METH_VARARGS },
	{ "freyjaMeshPolygonMaterial", py_freyjaMeshPolygonMaterial, METH_VARARGS },
	{ "freyjaMeshPolygonClearFlag1u", py_freyjaMeshPolygonClearFlag1u, METH_VARARGS },
	{ "freyjaMeshPolygonSetFlag1u", py_freyjaMeshPolygonSetFlag1u, METH_VARARGS },
	{ "freyjaMeshPolygonGroup1u", py_freyjaMeshPolygonGroup1u, METH_VARARGS },
	{ "freyjaMeshUVMapPlanar", py_freyjaMeshUVMapPlanar, METH_VARARGS },
	{ "freyjaMeshUVMapSpherical", py_freyjaMeshUVMapSpherical, METH_VARARGS },
	{ "freyjaMeshUVMapCylindrical", py_freyjaMeshUVMapCylindrical, METH_VARARGS },
	{ "freyjaMeshTesselateTriangles", py_freyjaMeshTesselateTriangles, METH_VARARGS },
	{ "freyjaMeshNormalFlip", py_freyjaMeshNormalFlip, METH_VARARGS },
	{ "freyjaMeshGenerateVertexNormals", py_freyjaMeshGenerateVertexNormals, METH_VARARGS },
	{ "freyjaMeshPolygonExtrudeQuad1f", py_freyjaMeshPolygonExtrudeQuad1f, METH_VARARGS },
	{ "freyjaMeshVertexWeight", py_freyjaMeshVertexWeight, METH_VARARGS },
	{ "freyjaMeshTexCoordWeld", py_freyjaMeshTexCoordWeld, METH_VARARGS },
	{ "freyjaMeshVertexWeld", py_freyjaMeshVertexWeld, METH_VARARGS },
	{ "freyjaMeshUpdateBlendVertices", py_freyjaMeshUpdateBlendVertices, METH_VARARGS },
	{ "freyjaMeshVertexTrackNew", py_freyjaMeshVertexTrackNew, METH_VARARGS },
	{ "freyjaMeshVertexKeyFrameNew", py_freyjaMeshVertexKeyFrameNew, METH_VARARGS },
	{ "freyjaMeshVertexKeyFrame3f", py_freyjaMeshVertexKeyFrame3f, METH_VARARGS },
	{ "freyjaMeshPolygonSplit", py_freyjaMeshPolygonSplit, METH_VARARGS },
	{ "freyjaGetMeshCount", py_freyjaGetMeshCount, METH_VARARGS },
	{ "freyjaGetMeshBoundingBox", py_freyjaGetMeshBoundingBox, METH_VARARGS },
	{ "freyjaGetMeshBoundingSphere", py_freyjaGetMeshBoundingSphere, METH_VARARGS },
	{ "freyjaGetMeshFlags", py_freyjaGetMeshFlags, METH_VARARGS },
	{ "freyjaGetMeshPosition", py_freyjaGetMeshPosition, METH_VARARGS },
	{ "freyjaGetMeshNameString", py_freyjaGetMeshNameString, METH_VARARGS },
	{ "freyjaGetMeshName1s", py_freyjaGetMeshName1s, METH_VARARGS },
	{ "freyjaGetMeshVertexFlags", py_freyjaGetMeshVertexFlags, METH_VARARGS },
	{ "freyjaGetMeshVertexPos3fv", py_freyjaGetMeshVertexPos3fv, METH_VARARGS },
	{ "freyjaGetMeshVertexNormal3fv", py_freyjaGetMeshVertexNormal3fv, METH_VARARGS },
	{ "freyjaGetMeshVertexTexCoord3fv", py_freyjaGetMeshVertexTexCoord3fv, METH_VARARGS },
	{ "freyjaGetMeshVertexTexCoord", py_freyjaGetMeshVertexTexCoord, METH_VARARGS },
	{ "freyjaGetMeshVertexPolygonRefCount", py_freyjaGetMeshVertexPolygonRefCount, METH_VARARGS },
	{ "freyjaGetMeshVertexPolygonRefIndex", py_freyjaGetMeshVertexPolygonRefIndex, METH_VARARGS },
	{ "freyjaGetMeshTexCoord2fv", py_freyjaGetMeshTexCoord2fv, METH_VARARGS },
	{ "freyjaGetMeshPolygonFlags", py_freyjaGetMeshPolygonFlags, METH_VARARGS },
	{ "freyjaGetMeshPolygonGroup", py_freyjaGetMeshPolygonGroup, METH_VARARGS },
	{ "freyjaGetMeshPolygonEdgeCount", py_freyjaGetMeshPolygonEdgeCount, METH_VARARGS },
	{ "freyjaGetMeshPolygonVertexCount", py_freyjaGetMeshPolygonVertexCount, METH_VARARGS },
	{ "freyjaGetMeshPolygonVertexIndex", py_freyjaGetMeshPolygonVertexIndex, METH_VARARGS },
	{ "freyjaGetMeshPolygonTexCoordCount", py_freyjaGetMeshPolygonTexCoordCount, METH_VARARGS },
	{ "freyjaGetMeshPolygonTexCoordIndex", py_freyjaGetMeshPolygonTexCoordIndex, METH_VARARGS },
	{ "freyjaGetMeshPolygonMaterial", py_freyjaGetMeshPolygonMaterial, METH_VARARGS },
	{ "freyjaGetMeshTexCoordCount", py_freyjaGetMeshTexCoordCount, METH_VARARGS },
	{ "freyjaGetMeshVertexCount", py_freyjaGetMeshVertexCount, METH_VARARGS },
	{ "freyjaGetMeshTexCoordCount", py_freyjaGetMeshTexCoordCount, METH_VARARGS },
	{ "freyjaGetMeshPolygonCount", py_freyjaGetMeshPolygonCount, METH_VARARGS },
	{ "freyjaGetMeshBlendVertices", py_freyjaGetMeshBlendVertices, METH_VARARGS },
	{ "freyjaGetMeshWeight", py_freyjaGetMeshWeight, METH_VARARGS },
	{ "freyjaGetMeshWeightCount", py_freyjaGetMeshWeightCount, METH_VARARGS },
	{ "freyjaGetMeshVertexTrackCount", py_freyjaGetMeshVertexTrackCount, METH_VARARGS },
	{ "freyjaGetMeshVertexKeyFrameCount", py_freyjaGetMeshVertexKeyFrameCount, METH_VARARGS },
	{ "freyjaMeshCreateSheet", py_freyjaMeshCreateSheet, METH_VARARGS },
	{ "freyjaMeshCreateCube", py_freyjaMeshCreateCube, METH_VARARGS },
	{ "freyjaMeshCreateCircle", py_freyjaMeshCreateCircle, METH_VARARGS },
	{ "freyjaMeshCreateCone", py_freyjaMeshCreateCone, METH_VARARGS },
	{ "freyjaMeshCreateCylinder", py_freyjaMeshCreateCylinder, METH_VARARGS },
	{ "freyjaMeshCreateSphere", py_freyjaMeshCreateSphere, METH_VARARGS },
	{ "freyjaMeshCreateTube", py_freyjaMeshCreateTube, METH_VARARGS },
	{ "freyjaGetMeshClass", py_freyjaGetMeshClass, METH_VARARGS },
	{ "freyjaGetMeshWeightClass", py_freyjaGetMeshWeightClass, METH_VARARGS },
	{ "freyjaGetMeshVertexClass", py_freyjaGetMeshVertexClass, METH_VARARGS },
	{ "freyjaGetMeshFaceClass", py_freyjaGetMeshFaceClass, METH_VARARGS },
	{ "freyjaMeshLoadChunkJA", py_freyjaMeshLoadChunkJA, METH_VARARGS },
	{ "freyjaMeshSaveChunkJA", py_freyjaMeshSaveChunkJA, METH_VARARGS },
	{ "freyjaMeshSaveChunkTextJA", py_freyjaMeshSaveChunkTextJA, METH_VARARGS },
	{ "freyjaMeshLoadChunkTextJA", py_freyjaMeshLoadChunkTextJA, METH_VARARGS },
	{ NULL }
};


PyObject *py_freyjaGetSkeletonCount(PyObject *self, PyObject *args)
{
	return PyInt_FromLong(freyjaGetSkeletonCount());
}


PyObject *py_freyjaGetSkeletonBoneCount(PyObject *self, PyObject *args)
{
	index_t skeletonIndex;

	if (!PyArg_ParseTuple(args, "i", &skeletonIndex))
		return NULL;

	return PyInt_FromLong(freyjaGetSkeletonBoneCount(&skeletonIndex));
}


PyObject *py_freyjaGetSkeletonBoneIndex(PyObject *self, PyObject *args)
{
	index_t skeletonIndex;
	uint32 element;

	if (!PyArg_ParseTuple(args, "ii", &skeletonIndex, &element))
		return NULL;

	return PyInt_FromLong(freyjaGetSkeletonBoneIndex(&skeletonIndex, &element));
}


PyObject *py_freyjaGetSkeletonRootIndex(PyObject *self, PyObject *args)
{
	index_t skeletonIndex;

	if (!PyArg_ParseTuple(args, "i", &skeletonIndex))
		return NULL;

	return PyInt_FromLong(freyjaGetSkeletonRootIndex(&skeletonIndex));
}


PyObject *py_char*(PyObject *self, PyObject *args)
{
	index_t skeleton;

	if (!PyArg_ParseTuple(args, "i", &skeleton))
		return NULL;

	freyjaGetSkeletonName(&skeleton);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetKeyFrameCount(PyObject *self, PyObject *args)
{
	return PyInt_FromLong(freyjaGetKeyFrameCount());
}


PyObject *py_freyjaGetKeyFrameTime(PyObject *self, PyObject *args)
{
	index_t keyframeIndex;

	if (!PyArg_ParseTuple(args, "i", &keyframeIndex))
		return NULL;

	freyjaGetKeyFrameTime(&keyframeIndex);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetKeyFrameFlags(PyObject *self, PyObject *args)
{
	index_t keyframeIndex;

	if (!PyArg_ParseTuple(args, "i", &keyframeIndex))
		return NULL;

	return PyInt_FromLong(freyjaGetKeyFrameFlags(&keyframeIndex));
}


PyObject *py_freyjaGetModelCount(PyObject *self, PyObject *args)
{
	return PyInt_FromLong(freyjaGetModelCount());
}


PyObject *py_freyjaGetModelFlags(PyObject *self, PyObject *args)
{
	index_t model;

	if (!PyArg_ParseTuple(args, "i", &model))
		return NULL;

	return PyInt_FromLong(freyjaGetModelFlags(&model));
}


PyObject *py_freyjaGetModelMeshCount(PyObject *self, PyObject *args)
{
	index_t model;

	if (!PyArg_ParseTuple(args, "i", &model))
		return NULL;

	return PyInt_FromLong(freyjaGetModelMeshCount(&model));
}


PyObject *py_freyjaGetModelMeshIndex(PyObject *self, PyObject *args)
{
	index_t model;
	uint32 element;

	if (!PyArg_ParseTuple(args, "ii", &model, &element))
		return NULL;

	return PyInt_FromLong(freyjaGetModelMeshIndex(&model, &element));
}


PyObject *py_freyjaGetModelSkeleton(PyObject *self, PyObject *args)
{
	index_t model;

	if (!PyArg_ParseTuple(args, "i", &model))
		return NULL;

	return PyInt_FromLong(freyjaGetModelSkeleton(&model));
}


PyObject *py_freyjaGetBoneCount(PyObject *self, PyObject *args)
{
	return PyInt_FromLong(freyjaGetBoneCount());
}


PyObject *py_freyjaGetBoneRotationQuat4fv(PyObject *self, PyObject *args)
{
	index_t boneIndex;
	vec4_t wxyz;

	if (!PyArg_ParseTuple(args, "iffff", &boneIndex, wxyz+0, wxyz+1, wxyz+2, wxyz+3))
		return NULL;

	freyjaGetBoneRotationQuat4fv(&boneIndex, wxyz+0, wxyz+1, wxyz+2, wxyz+3);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetBoneRotationEuler3fv(PyObject *self, PyObject *args)
{
	index_t boneIndex;
	vec3_t phr;

	if (!PyArg_ParseTuple(args, "ifff", &boneIndex, phr+0, phr+1, phr+2))
		return NULL;

	freyjaGetBoneRotationEuler3fv(&boneIndex, phr+0, phr+1, phr+2);
	return PyInt_FromLong(0);
}


PyObject *py_char*(PyObject *self, PyObject *args)
{
	index_t boneIndex;

	if (!PyArg_ParseTuple(args, "i", &boneIndex))
		return NULL;

	freyjaGetBoneNameString(&boneIndex);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetBoneName(PyObject *self, PyObject *args)
{
	index_t boneIndex;
	uint32 size;
	char* name;

	if (!PyArg_ParseTuple(args, "iii", &boneIndex, &size, &name))
		return NULL;

	freyjaGetBoneName(&boneIndex, &size, &name);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetBoneParent(PyObject *self, PyObject *args)
{
	index_t boneIndex;

	if (!PyArg_ParseTuple(args, "i", &boneIndex))
		return NULL;

	return PyInt_FromLong(freyjaGetBoneParent(&boneIndex));
}


PyObject *py_freyjaGetBoneBindPose16fv(PyObject *self, PyObject *args)
{
	index_t boneIndex;

	if (!PyArg_ParseTuple(args, "i", &boneIndex))
		return NULL;

	freyjaGetBoneBindPose16fv(&boneIndex);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetBoneWorldPos3fv(PyObject *self, PyObject *args)
{
	index_t boneIndex;
	vec3_t xyz;

	if (!PyArg_ParseTuple(args, "ifff", &boneIndex, xyz+0, xyz+1, xyz+2))
		return NULL;

	freyjaGetBoneWorldPos3fv(&boneIndex, xyz+0, xyz+1, xyz+2);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetBoneTranslation3fv(PyObject *self, PyObject *args)
{
	index_t boneIndex;
	vec3_t xyz;

	if (!PyArg_ParseTuple(args, "ifff", &boneIndex, xyz+0, xyz+1, xyz+2))
		return NULL;

	freyjaGetBoneTranslation3fv(&boneIndex, xyz+0, xyz+1, xyz+2);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetBoneSkeletonIndex(PyObject *self, PyObject *args)
{
	index_t boneIndex;

	if (!PyArg_ParseTuple(args, "i", &boneIndex))
		return NULL;

	return PyInt_FromLong(freyjaGetBoneSkeletonIndex(&boneIndex));
}


PyObject *py_freyjaGetBoneChild(PyObject *self, PyObject *args)
{
	index_t boneIndex;
	uint32 element;

	if (!PyArg_ParseTuple(args, "ii", &boneIndex, &element))
		return NULL;

	return PyInt_FromLong(freyjaGetBoneChild(&boneIndex, &element));
}


PyObject *py_freyjaGetBoneChildCount(PyObject *self, PyObject *args)
{
	index_t boneIndex;

	if (!PyArg_ParseTuple(args, "i", &boneIndex))
		return NULL;

	return PyInt_FromLong(freyjaGetBoneChildCount(&boneIndex));
}


PyObject *py_freyjaGetLightCount(PyObject *self, PyObject *args)
{
	return PyInt_FromLong(freyjaGetLightCount());
}


PyObject *py_freyjaGetLightPosition4v(PyObject *self, PyObject *args)
{
	index_t lightIndex;
	vec4_t position;

	if (!PyArg_ParseTuple(args, "iffff", &lightIndex, position+0, position+1, position+2, position+3))
		return NULL;

	freyjaGetLightPosition4v(&lightIndex, position+0, position+1, position+2, position+3);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetLightAmbient(PyObject *self, PyObject *args)
{
	index_t lightIndex;
	vec4_t ambient;

	if (!PyArg_ParseTuple(args, "iffff", &lightIndex, ambient+0, ambient+1, ambient+2, ambient+3))
		return NULL;

	freyjaGetLightAmbient(&lightIndex, ambient+0, ambient+1, ambient+2, ambient+3);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetLightDiffuse(PyObject *self, PyObject *args)
{
	index_t lightIndex;
	vec4_t diffuse;

	if (!PyArg_ParseTuple(args, "iffff", &lightIndex, diffuse+0, diffuse+1, diffuse+2, diffuse+3))
		return NULL;

	freyjaGetLightDiffuse(&lightIndex, diffuse+0, diffuse+1, diffuse+2, diffuse+3);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetLightSpecular(PyObject *self, PyObject *args)
{
	index_t lightIndex;
	vec4_t specular;

	if (!PyArg_ParseTuple(args, "iffff", &lightIndex, specular+0, specular+1, specular+2, specular+3))
		return NULL;

	freyjaGetLightSpecular(&lightIndex, specular+0, specular+1, specular+2, specular+3);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMaterialCount(PyObject *self, PyObject *args)
{
	return PyInt_FromLong(freyjaGetMaterialCount());
}


PyObject *py_freyjaGetMaterialIndex(PyObject *self, PyObject *args)
{
	index_t material;
	uint32 element;

	if (!PyArg_ParseTuple(args, "ii", &material, &element))
		return NULL;

	return PyInt_FromLong(freyjaGetMaterialIndex(&material, &element));
}


PyObject *py_char*(PyObject *self, PyObject *args)
{
	index_t material;

	if (!PyArg_ParseTuple(args, "i", &material))
		return NULL;

	freyjaGetMaterialName(&material);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMaterialFlags(PyObject *self, PyObject *args)
{
	index_t material;

	if (!PyArg_ParseTuple(args, "i", &material))
		return NULL;

	return PyInt_FromLong(freyjaGetMaterialFlags(&material));
}


PyObject *py_freyjaGetMaterialTexture(PyObject *self, PyObject *args)
{
	index_t material;

	if (!PyArg_ParseTuple(args, "i", &material))
		return NULL;

	return PyInt_FromLong(freyjaGetMaterialTexture(&material));
}


PyObject *py_char*(PyObject *self, PyObject *args)
{
	index_t material;

	if (!PyArg_ParseTuple(args, "i", &material))
		return NULL;

	freyjaGetMaterialTextureName(&material);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMaterialAmbient(PyObject *self, PyObject *args)
{
	index_t material;
	vec4_t ambient;

	if (!PyArg_ParseTuple(args, "iffff", &material, ambient+0, ambient+1, ambient+2, ambient+3))
		return NULL;

	freyjaGetMaterialAmbient(&material, ambient+0, ambient+1, ambient+2, ambient+3);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMaterialDiffuse(PyObject *self, PyObject *args)
{
	index_t material;
	vec4_t diffuse;

	if (!PyArg_ParseTuple(args, "iffff", &material, diffuse+0, diffuse+1, diffuse+2, diffuse+3))
		return NULL;

	freyjaGetMaterialDiffuse(&material, diffuse+0, diffuse+1, diffuse+2, diffuse+3);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMaterialSpecular(PyObject *self, PyObject *args)
{
	index_t material;
	vec4_t specular;

	if (!PyArg_ParseTuple(args, "iffff", &material, specular+0, specular+1, specular+2, specular+3))
		return NULL;

	freyjaGetMaterialSpecular(&material, specular+0, specular+1, specular+2, specular+3);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMaterialEmissive(PyObject *self, PyObject *args)
{
	index_t material;
	vec4_t emissive;

	if (!PyArg_ParseTuple(args, "iffff", &material, emissive+0, emissive+1, emissive+2, emissive+3))
		return NULL;

	freyjaGetMaterialEmissive(&material, emissive+0, emissive+1, emissive+2, emissive+3);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMaterialShininess(PyObject *self, PyObject *args)
{
	index_t material;

	if (!PyArg_ParseTuple(args, "i", &material))
		return NULL;

	freyjaGetMaterialShininess(&material);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMaterialTransparency(PyObject *self, PyObject *args)
{
	index_t material;

	if (!PyArg_ParseTuple(args, "i", &material))
		return NULL;

	freyjaGetMaterialTransparency(&material);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMaterialBlendSource(PyObject *self, PyObject *args)
{
	index_t material;

	if (!PyArg_ParseTuple(args, "i", &material))
		return NULL;

	freyjaGetMaterialBlendSource(&material);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMaterialBlendDestination(PyObject *self, PyObject *args)
{
	index_t material;

	if (!PyArg_ParseTuple(args, "i", &material))
		return NULL;

	freyjaGetMaterialBlendDestination(&material);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshCount(PyObject *self, PyObject *args)
{
	return PyInt_FromLong(freyjaGetMeshCount());
}


PyObject *py_freyjaGetMeshBoundingBox(PyObject *self, PyObject *args)
{
	index_t mesh;
	vec3_t min;
	vec3_t max;

	if (!PyArg_ParseTuple(args, "iffffff", &mesh, min+0, min+1, min+2, max+0, max+1, max+2))
		return NULL;

	freyjaGetMeshBoundingBox(&mesh, min+0, min+1, min+2, max+0, max+1, max+2);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshBoundingSphere(PyObject *self, PyObject *args)
{
	index_t mesh;

	if (!PyArg_ParseTuple(args, "i", &mesh))
		return NULL;

	freyjaGetMeshBoundingSphere(&mesh);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshFlags(PyObject *self, PyObject *args)
{
	index_t mesh;

	if (!PyArg_ParseTuple(args, "i", &mesh))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshFlags(&mesh));
}


PyObject *py_freyjaGetMeshPosition(PyObject *self, PyObject *args)
{
	index_t mesh;
	vec3_t xyz;

	if (!PyArg_ParseTuple(args, "ifff", &mesh, xyz+0, xyz+1, xyz+2))
		return NULL;

	freyjaGetMeshPosition(&mesh, xyz+0, xyz+1, xyz+2);
	return PyInt_FromLong(0);
}


PyObject *py_char*(PyObject *self, PyObject *args)
{
	index_t meshIndex;

	if (!PyArg_ParseTuple(args, "i", &meshIndex))
		return NULL;

	freyjaGetMeshNameString(&meshIndex);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshName1s(PyObject *self, PyObject *args)
{
	index_t mesh;
	uint32 lenght;
	char* name;

	if (!PyArg_ParseTuple(args, "iii", &mesh, &lenght, &name))
		return NULL;

	freyjaGetMeshName1s(&mesh, &lenght, &name);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshVertexFlags(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t vertex;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &vertex))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshVertexFlags(&mesh, &vertex));
}


PyObject *py_freyjaGetMeshVertexPos3fv(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t vertex;
	vec3_t xyz;

	if (!PyArg_ParseTuple(args, "iifff", &mesh, &vertex, xyz+0, xyz+1, xyz+2))
		return NULL;

	freyjaGetMeshVertexPos3fv(&mesh, &vertex, xyz+0, xyz+1, xyz+2);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshVertexNormal3fv(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t vertex;
	vec3_t xyz;

	if (!PyArg_ParseTuple(args, "iifff", &mesh, &vertex, xyz+0, xyz+1, xyz+2))
		return NULL;

	freyjaGetMeshVertexNormal3fv(&mesh, &vertex, xyz+0, xyz+1, xyz+2);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshVertexTexCoord3fv(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t vert;
	vec3_t xyz;

	if (!PyArg_ParseTuple(args, "iifff", &mesh, &vert, xyz+0, xyz+1, xyz+2))
		return NULL;

	freyjaGetMeshVertexTexCoord3fv(&mesh, &vert, xyz+0, xyz+1, xyz+2);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshVertexTexCoord(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t vertex;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &vertex))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshVertexTexCoord(&mesh, &vertex));
}


PyObject *py_freyjaGetMeshVertexPolygonRefCount(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t vertex;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &vertex))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshVertexPolygonRefCount(&mesh, &vertex));
}


PyObject *py_freyjaGetMeshVertexPolygonRefIndex(PyObject *self, PyObject *args)
{
	index_t mesh;

	if (!PyArg_ParseTuple(args, "i", &mesh))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshVertexPolygonRefIndex(&mesh));
}


PyObject *py_freyjaGetMeshTexCoord2fv(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t texcoord;
	vec2_t uv;

	if (!PyArg_ParseTuple(args, "iiff", &mesh, &texcoord, uv+0, uv+1))
		return NULL;

	freyjaGetMeshTexCoord2fv(&mesh, &texcoord, uv+0, uv+1);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshPolygonFlags(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t polygon;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &polygon))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshPolygonFlags(&mesh, &polygon));
}


PyObject *py_freyjaGetMeshPolygonGroup(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t polygon;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &polygon))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshPolygonGroup(&mesh, &polygon));
}


PyObject *py_freyjaGetMeshPolygonEdgeCount(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t polygon;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &polygon))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshPolygonEdgeCount(&mesh, &polygon));
}


PyObject *py_freyjaGetMeshPolygonVertexCount(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t polygon;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &polygon))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshPolygonVertexCount(&mesh, &polygon));
}


PyObject *py_freyjaGetMeshPolygonVertexIndex(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t polygon;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &polygon))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshPolygonVertexIndex(&mesh, &polygon));
}


PyObject *py_freyjaGetMeshPolygonTexCoordCount(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t polygon;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &polygon))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshPolygonTexCoordCount(&mesh, &polygon));
}


PyObject *py_freyjaGetMeshPolygonTexCoordIndex(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t polygon;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &polygon))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshPolygonTexCoordIndex(&mesh, &polygon));
}


PyObject *py_freyjaGetMeshPolygonMaterial(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t polygon;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &polygon))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshPolygonMaterial(&mesh, &polygon));
}


PyObject *py_freyjaGetMeshTexCoordCount(PyObject *self, PyObject *args)
{
	index_t mesh;

	if (!PyArg_ParseTuple(args, "i", &mesh))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshTexCoordCount(&mesh));
}


PyObject *py_freyjaGetMeshVertexCount(PyObject *self, PyObject *args)
{
	index_t mesh;

	if (!PyArg_ParseTuple(args, "i", &mesh))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshVertexCount(&mesh));
}


PyObject *py_freyjaGetMeshTexCoordCount(PyObject *self, PyObject *args)
{
	index_t mesh;

	if (!PyArg_ParseTuple(args, "i", &mesh))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshTexCoordCount(&mesh));
}


PyObject *py_freyjaGetMeshPolygonCount(PyObject *self, PyObject *args)
{
	index_t mesh;

	if (!PyArg_ParseTuple(args, "i", &mesh))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshPolygonCount(&mesh));
}


PyObject *py_freyjaGetMeshBlendVertices(PyObject *self, PyObject *args)
{
	index_t mesh;

	if (!PyArg_ParseTuple(args, "i", &mesh))
		return NULL;

	freyjaGetMeshBlendVertices(&mesh);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshWeight(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t weight;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &weight))
		return NULL;

	freyjaGetMeshWeight(&mesh, &weight);
	return PyInt_FromLong(0);
}


PyObject *py_freyjaGetMeshWeightCount(PyObject *self, PyObject *args)
{
	index_t mesh;

	if (!PyArg_ParseTuple(args, "i", &mesh))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshWeightCount(&mesh));
}


PyObject *py_freyjaGetMeshVertexTrackCount(PyObject *self, PyObject *args)
{
	index_t mesh;

	if (!PyArg_ParseTuple(args, "i", &mesh))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshVertexTrackCount(&mesh));
}


PyObject *py_freyjaGetMeshVertexKeyFrameCount(PyObject *self, PyObject *args)
{
	index_t mesh;
	index_t track;

	if (!PyArg_ParseTuple(args, "ii", &mesh, &track))
		return NULL;

	return PyInt_FromLong(freyjaGetMeshVertexKeyFrameCount(&mesh, &track));
}


PyObject *Freyja_Plugin_Gobals()
{
	PyObject *module, *dict, *tmp;

	module = Py_InitModule("FreyjaModeler", Plugin_methods);
	dict = PyModule_GetDict(module);
	
	/* Append gobal constants you want python to see */
	tmp = PyInt_FromLong(FREYJA_MODEL);
	PyDict_SetItemString(dict, "FREYJA_MODEL", tmp);
	Py_DECREF(tmp);
	
	return module;
}


int freyjaPython1s(const char *plugin, const char *symbol, const char *s)
{
	PyObject *module, *dict, *tmp;

	/* Start up python */
	Py_Initialize();
	module = Freyja_Plugin_Gobals();
	dict = PyModule_GetDict(module);

	/* Append gobal constants, pass <s> as <symbol> in python */
	tmp = PyString_FromFormat(s);
	PyDict_SetItemString(dict, symbol, tmp);
	Py_DECREF(tmp);

	freyjaPrintMessage("[Module '%s' opened.]", plugin);
	PyRun_SimpleFile(f, plugin);
	Py_Finalize();
}


