Document: libmgtk
Title: Debian libmgtk Manual
Author: <insert document author here>
Abstract: This manual describes what libmgtk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libmgtk/libmgtk.sgml.gz

Format: postscript
Files: /usr/share/doc/libmgtk/libmgtk.ps.gz

Format: text
Files: /usr/share/doc/libmgtk/libmgtk.text.gz

Format: HTML
Index: /usr/share/doc/libmgtk/html/index.html
Files: /usr/share/doc/libmgtk/html/*.html

  
